### ISSUE TITLE
Restyling webapp SCK 2.0

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/smartcitizen-kit-20#8]
@marcelirodriguez:

https://fablabbcn.github.io/smartcitizen-kit-20/esp/build_data/

Add padding on the content: 20px (top) 30px (left) 30px (right)
- [x] Change top bar color to #262626
-  [x]  Change CYAN text color to #0C2EFB
-  [x]  Change CYAN button color to #FFC100 and the text on it to #262626
-  [x]  Change GREEN alert color to #8CC252
-  [x]  Change RED alert color to #FF3D4C
-  [x]  Change the logo for the full-white version: https://smartcitizen.me/assets/images/smartcitizen_logo.svg

Thoughts:
- [ ] Should we use a better icon for the (i) in the top right? Because this also includes some **advanced** functions like force updating the firmware.
- [ ] Are all colors correct? 
- [ ] Is this the final font? We can only use **Web Safe fonts** because of size limitations

**Comment by viktorsmari** [comment]
Should we add a font? How much space would it take?
